# Generated by Django 6.0 on 2025-12-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioproject",
            name="image",
            field=models.URLField(help_text="Image URL", max_length=500),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="link",
            field=models.URLField(
                blank=True, help_text="Project demo link", max_length=500
            ),
        ),
    ]
