# Generated by Django 5.0.14 on 2026-01-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0002_alter_portfolioproject_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(help_text="Plan name in Chinese", max_length=100),
                ),
                (
                    "name_en",
                    models.CharField(help_text="Plan name in English", max_length=100),
                ),
                (
                    "description_zh",
                    models.TextField(help_text="Plan description in Chinese"),
                ),
                (
                    "description_en",
                    models.TextField(help_text="Plan description in English"),
                ),
                (
                    "price_one_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="One-time price in TWD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly price in TWD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text='List of features: [{"name_zh": "...", "name_en": "...", "included": true}]',
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("one_time", "One-time"),
                            ("monthly", "Monthly"),
                            ("both", "Both"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False, help_text="Mark as recommended plan"
                    ),
                ),
                (
                    "cta_text_zh",
                    models.CharField(
                        default="立即開始",
                        help_text="CTA button text in Chinese",
                        max_length=50,
                    ),
                ),
                (
                    "cta_text_en",
                    models.CharField(
                        default="Get Started",
                        help_text="CTA button text in English",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
