# Generated by Django 6.0.3 on 2026-03-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='plan_type',
            field=models.CharField(default='basic', help_text='CSS class type: basic, standard, advanced', max_length=20),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='sub_note',
            field=models.CharField(blank=True, help_text='Small note below price, supports HTML', max_length=200),
        ),
    ]
